'use client';

import { useState } from 'react';
import { Download, Copy, Check, Share2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { SalaryInput, CalculationResult } from '@/lib/tax-calculators/types';
import { formatCurrency, formatPercentage } from '@/lib/utils/formatters';

interface ExportButtonProps {
  input: SalaryInput;
  result: CalculationResult;
}

export function ExportButton({ input, result }: ExportButtonProps) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  const generateTextSummary = () => {
    return `Take Home Pay Calculator Results
================================

Gross Annual Salary: ${formatCurrency(result.grossAnnual)}
State: ${input.state}
Filing Status: ${input.filingStatus.replace('_', ' ')}

TAX BREAKDOWN
-------------
Federal Income Tax: ${formatCurrency(result.federalTax)}
State Income Tax: ${formatCurrency(result.stateTax)}
Social Security: ${formatCurrency(result.socialSecurity)}
Medicare: ${formatCurrency(result.medicare)}
${result.totalDeductions > 0 ? `Pre-Tax Deductions: ${formatCurrency(result.totalDeductions)}` : ''}

TOTALS
------
Total Taxes: ${formatCurrency(result.totalTax)}
Effective Tax Rate: ${formatPercentage(result.effectiveTaxRate)}
Marginal Tax Rate: ${formatPercentage(result.marginalTaxRate)}

NET INCOME
----------
Annual: ${formatCurrency(result.netAnnual)}
Monthly: ${formatCurrency(result.netMonthly)}
Bi-Weekly: ${formatCurrency(result.netBiweekly)}
Weekly: ${formatCurrency(result.netWeekly)}

Generated by TakeHomePay.com
`;
  };

  const handleCopy = async () => {
    const text = generateTextSummary();
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleShare = async () => {
    const text = `My take-home pay on a ${formatCurrency(result.grossAnnual)} salary in ${input.state} is ${formatCurrency(result.netAnnual)} per year (${formatPercentage(result.effectiveTaxRate)} effective tax rate). Calculate yours at TakeHomePay.com`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Take Home Pay Calculator',
          text,
        });
      } catch {
        // User cancelled or error
      }
    } else {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className="flex-1">
          <Download className="h-4 w-4 mr-2" />
          Export
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle>Export Results</DialogTitle>
          <DialogDescription>
            Copy your calculation results or share them with others.
          </DialogDescription>
        </DialogHeader>
        <div className="py-4 space-y-4">
          {/* Preview */}
          <div className="p-4 bg-muted rounded-lg font-mono text-xs whitespace-pre-wrap max-h-[300px] overflow-y-auto">
            {generateTextSummary()}
          </div>

          {/* Action Buttons */}
          <div className="flex gap-4">
            <Button onClick={handleCopy} className="flex-1">
              {copied ? (
                <>
                  <Check className="h-4 w-4 mr-2" />
                  Copied!
                </>
              ) : (
                <>
                  <Copy className="h-4 w-4 mr-2" />
                  Copy to Clipboard
                </>
              )}
            </Button>
            <Button onClick={handleShare} variant="secondary" className="flex-1">
              <Share2 className="h-4 w-4 mr-2" />
              Share
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
