// Cost of Living Index Data (US Average = 100)
// Sources: Bureau of Economic Analysis Regional Price Parities, C2ER Cost of Living Index

export interface CostOfLivingData {
  state: string;
  stateCode: string;
  overallIndex: number;
  housing: number;
  groceries: number;
  utilities: number;
  transportation: number;
  healthcare: number;
  miscellaneous: number;
}

// Cost of living indices by state (US Average = 100)
export const costOfLivingByState: Record<string, CostOfLivingData> = {
  AL: {
    state: 'Alabama',
    stateCode: 'AL',
    overallIndex: 89.3,
    housing: 72.5,
    groceries: 95.4,
    utilities: 103.2,
    transportation: 89.8,
    healthcare: 91.5,
    miscellaneous: 92.1,
  },
  AK: {
    state: 'Alaska',
    stateCode: 'AK',
    overallIndex: 127.1,
    housing: 134.2,
    groceries: 131.8,
    utilities: 169.5,
    transportation: 118.4,
    healthcare: 151.2,
    miscellaneous: 108.3,
  },
  AZ: {
    state: 'Arizona',
    stateCode: 'AZ',
    overallIndex: 102.2,
    housing: 107.8,
    groceries: 96.5,
    utilities: 103.1,
    transportation: 99.8,
    healthcare: 95.2,
    miscellaneous: 99.4,
  },
  AR: {
    state: 'Arkansas',
    stateCode: 'AR',
    overallIndex: 89.0,
    housing: 72.8,
    groceries: 93.2,
    utilities: 99.5,
    transportation: 87.6,
    healthcare: 89.1,
    miscellaneous: 93.8,
  },
  CA: {
    state: 'California',
    stateCode: 'CA',
    overallIndex: 142.2,
    housing: 196.5,
    groceries: 105.1,
    utilities: 127.3,
    transportation: 132.8,
    healthcare: 109.4,
    miscellaneous: 110.5,
  },
  CO: {
    state: 'Colorado',
    stateCode: 'CO',
    overallIndex: 105.4,
    housing: 118.2,
    groceries: 99.8,
    utilities: 92.1,
    transportation: 100.5,
    healthcare: 102.8,
    miscellaneous: 101.2,
  },
  CT: {
    state: 'Connecticut',
    stateCode: 'CT',
    overallIndex: 112.8,
    housing: 122.5,
    groceries: 103.2,
    utilities: 126.8,
    transportation: 106.4,
    healthcare: 115.2,
    miscellaneous: 105.8,
  },
  DE: {
    state: 'Delaware',
    stateCode: 'DE',
    overallIndex: 102.4,
    housing: 105.8,
    groceries: 101.2,
    utilities: 108.5,
    transportation: 101.8,
    healthcare: 103.2,
    miscellaneous: 99.5,
  },
  FL: {
    state: 'Florida',
    stateCode: 'FL',
    overallIndex: 102.8,
    housing: 107.2,
    groceries: 102.5,
    utilities: 101.8,
    transportation: 105.4,
    healthcare: 98.5,
    miscellaneous: 99.8,
  },
  GA: {
    state: 'Georgia',
    stateCode: 'GA',
    overallIndex: 93.4,
    housing: 85.2,
    groceries: 95.8,
    utilities: 99.2,
    transportation: 94.5,
    healthcare: 96.8,
    miscellaneous: 96.2,
  },
  HI: {
    state: 'Hawaii',
    stateCode: 'HI',
    overallIndex: 192.9,
    housing: 318.2,
    groceries: 152.5,
    utilities: 168.4,
    transportation: 133.8,
    healthcare: 119.5,
    miscellaneous: 124.8,
  },
  ID: {
    state: 'Idaho',
    stateCode: 'ID',
    overallIndex: 97.8,
    housing: 98.5,
    groceries: 94.2,
    utilities: 88.5,
    transportation: 96.8,
    healthcare: 98.2,
    miscellaneous: 99.5,
  },
  IL: {
    state: 'Illinois',
    stateCode: 'IL',
    overallIndex: 94.5,
    housing: 87.2,
    groceries: 97.8,
    utilities: 98.5,
    transportation: 103.2,
    healthcare: 98.5,
    miscellaneous: 97.8,
  },
  IN: {
    state: 'Indiana',
    stateCode: 'IN',
    overallIndex: 90.5,
    housing: 78.5,
    groceries: 93.5,
    utilities: 97.8,
    transportation: 92.5,
    healthcare: 94.2,
    miscellaneous: 95.8,
  },
  IA: {
    state: 'Iowa',
    stateCode: 'IA',
    overallIndex: 90.1,
    housing: 75.8,
    groceries: 94.2,
    utilities: 98.5,
    transportation: 93.8,
    healthcare: 98.5,
    miscellaneous: 94.5,
  },
  KS: {
    state: 'Kansas',
    stateCode: 'KS',
    overallIndex: 88.5,
    housing: 72.8,
    groceries: 93.5,
    utilities: 101.2,
    transportation: 91.5,
    healthcare: 96.8,
    miscellaneous: 93.2,
  },
  KY: {
    state: 'Kentucky',
    stateCode: 'KY',
    overallIndex: 92.1,
    housing: 79.5,
    groceries: 93.8,
    utilities: 98.2,
    transportation: 93.5,
    healthcare: 88.5,
    miscellaneous: 96.8,
  },
  LA: {
    state: 'Louisiana',
    stateCode: 'LA',
    overallIndex: 91.8,
    housing: 82.5,
    groceries: 97.2,
    utilities: 88.5,
    transportation: 92.8,
    healthcare: 89.2,
    miscellaneous: 95.5,
  },
  ME: {
    state: 'Maine',
    stateCode: 'ME',
    overallIndex: 112.5,
    housing: 118.5,
    groceries: 101.8,
    utilities: 118.2,
    transportation: 105.8,
    healthcare: 118.5,
    miscellaneous: 105.2,
  },
  MD: {
    state: 'Maryland',
    stateCode: 'MD',
    overallIndex: 118.2,
    housing: 142.5,
    groceries: 102.8,
    utilities: 115.8,
    transportation: 105.2,
    healthcare: 103.5,
    miscellaneous: 104.8,
  },
  MA: {
    state: 'Massachusetts',
    stateCode: 'MA',
    overallIndex: 135.0,
    housing: 176.5,
    groceries: 107.2,
    utilities: 125.8,
    transportation: 108.5,
    healthcare: 118.2,
    miscellaneous: 112.5,
  },
  MI: {
    state: 'Michigan',
    stateCode: 'MI',
    overallIndex: 90.2,
    housing: 76.8,
    groceries: 92.5,
    utilities: 101.8,
    transportation: 96.5,
    healthcare: 92.8,
    miscellaneous: 94.5,
  },
  MN: {
    state: 'Minnesota',
    stateCode: 'MN',
    overallIndex: 97.1,
    housing: 94.5,
    groceries: 99.8,
    utilities: 95.2,
    transportation: 98.5,
    healthcare: 97.2,
    miscellaneous: 98.5,
  },
  MS: {
    state: 'Mississippi',
    stateCode: 'MS',
    overallIndex: 84.8,
    housing: 65.5,
    groceries: 93.5,
    utilities: 96.8,
    transportation: 89.2,
    healthcare: 88.5,
    miscellaneous: 92.5,
  },
  MO: {
    state: 'Missouri',
    stateCode: 'MO',
    overallIndex: 89.8,
    housing: 75.2,
    groceries: 94.8,
    utilities: 102.5,
    transportation: 91.8,
    healthcare: 93.5,
    miscellaneous: 94.8,
  },
  MT: {
    state: 'Montana',
    stateCode: 'MT',
    overallIndex: 105.8,
    housing: 112.5,
    groceries: 100.2,
    utilities: 89.5,
    transportation: 98.2,
    healthcare: 108.5,
    miscellaneous: 103.8,
  },
  NE: {
    state: 'Nebraska',
    stateCode: 'NE',
    overallIndex: 92.5,
    housing: 82.8,
    groceries: 95.2,
    utilities: 96.8,
    transportation: 93.5,
    healthcare: 98.2,
    miscellaneous: 94.5,
  },
  NV: {
    state: 'Nevada',
    stateCode: 'NV',
    overallIndex: 104.2,
    housing: 112.8,
    groceries: 102.5,
    utilities: 95.8,
    transportation: 108.5,
    healthcare: 98.2,
    miscellaneous: 100.5,
  },
  NH: {
    state: 'New Hampshire',
    stateCode: 'NH',
    overallIndex: 112.8,
    housing: 125.5,
    groceries: 100.8,
    utilities: 118.5,
    transportation: 104.2,
    healthcare: 112.5,
    miscellaneous: 106.8,
  },
  NJ: {
    state: 'New Jersey',
    stateCode: 'NJ',
    overallIndex: 115.2,
    housing: 132.8,
    groceries: 103.5,
    utilities: 109.8,
    transportation: 110.5,
    healthcare: 108.2,
    miscellaneous: 108.5,
  },
  NM: {
    state: 'New Mexico',
    stateCode: 'NM',
    overallIndex: 91.2,
    housing: 82.5,
    groceries: 96.8,
    utilities: 93.5,
    transportation: 94.2,
    healthcare: 93.8,
    miscellaneous: 93.5,
  },
  NY: {
    state: 'New York',
    stateCode: 'NY',
    overallIndex: 123.5,
    housing: 155.8,
    groceries: 104.2,
    utilities: 112.5,
    transportation: 112.8,
    healthcare: 110.5,
    miscellaneous: 108.2,
  },
  NC: {
    state: 'North Carolina',
    stateCode: 'NC',
    overallIndex: 95.8,
    housing: 90.5,
    groceries: 96.2,
    utilities: 99.8,
    transportation: 93.5,
    healthcare: 98.2,
    miscellaneous: 97.5,
  },
  ND: {
    state: 'North Dakota',
    stateCode: 'ND',
    overallIndex: 97.2,
    housing: 92.5,
    groceries: 100.8,
    utilities: 90.5,
    transportation: 95.8,
    healthcare: 105.2,
    miscellaneous: 98.5,
  },
  OH: {
    state: 'Ohio',
    stateCode: 'OH',
    overallIndex: 90.8,
    housing: 77.2,
    groceries: 95.5,
    utilities: 98.2,
    transportation: 92.5,
    healthcare: 95.8,
    miscellaneous: 95.5,
  },
  OK: {
    state: 'Oklahoma',
    stateCode: 'OK',
    overallIndex: 87.5,
    housing: 70.8,
    groceries: 94.2,
    utilities: 98.5,
    transportation: 90.5,
    healthcare: 90.2,
    miscellaneous: 93.8,
  },
  OR: {
    state: 'Oregon',
    stateCode: 'OR',
    overallIndex: 113.2,
    housing: 128.5,
    groceries: 101.8,
    utilities: 92.5,
    transportation: 115.8,
    healthcare: 108.2,
    miscellaneous: 106.5,
  },
  PA: {
    state: 'Pennsylvania',
    stateCode: 'PA',
    overallIndex: 97.8,
    housing: 92.5,
    groceries: 100.5,
    utilities: 105.8,
    transportation: 101.2,
    healthcare: 96.5,
    miscellaneous: 97.2,
  },
  RI: {
    state: 'Rhode Island',
    stateCode: 'RI',
    overallIndex: 108.5,
    housing: 115.2,
    groceries: 102.8,
    utilities: 118.5,
    transportation: 104.5,
    healthcare: 108.2,
    miscellaneous: 103.8,
  },
  SC: {
    state: 'South Carolina',
    stateCode: 'SC',
    overallIndex: 94.2,
    housing: 85.8,
    groceries: 96.5,
    utilities: 106.8,
    transportation: 92.5,
    healthcare: 98.5,
    miscellaneous: 95.2,
  },
  SD: {
    state: 'South Dakota',
    stateCode: 'SD',
    overallIndex: 95.8,
    housing: 88.5,
    groceries: 100.2,
    utilities: 91.5,
    transportation: 96.5,
    healthcare: 102.8,
    miscellaneous: 96.2,
  },
  TN: {
    state: 'Tennessee',
    stateCode: 'TN',
    overallIndex: 90.5,
    housing: 78.2,
    groceries: 93.8,
    utilities: 97.5,
    transportation: 91.2,
    healthcare: 92.5,
    miscellaneous: 96.5,
  },
  TX: {
    state: 'Texas',
    stateCode: 'TX',
    overallIndex: 92.1,
    housing: 84.5,
    groceries: 93.2,
    utilities: 103.8,
    transportation: 93.5,
    healthcare: 95.8,
    miscellaneous: 95.2,
  },
  UT: {
    state: 'Utah',
    stateCode: 'UT',
    overallIndex: 101.5,
    housing: 108.5,
    groceries: 96.8,
    utilities: 87.5,
    transportation: 97.8,
    healthcare: 96.2,
    miscellaneous: 101.2,
  },
  VT: {
    state: 'Vermont',
    stateCode: 'VT',
    overallIndex: 114.8,
    housing: 122.8,
    groceries: 103.5,
    utilities: 125.2,
    transportation: 106.8,
    healthcare: 118.5,
    miscellaneous: 107.2,
  },
  VA: {
    state: 'Virginia',
    stateCode: 'VA',
    overallIndex: 103.8,
    housing: 110.5,
    groceries: 99.2,
    utilities: 103.8,
    transportation: 97.5,
    healthcare: 98.2,
    miscellaneous: 101.5,
  },
  WA: {
    state: 'Washington',
    stateCode: 'WA',
    overallIndex: 118.5,
    housing: 142.8,
    groceries: 104.5,
    utilities: 95.8,
    transportation: 118.2,
    healthcare: 108.5,
    miscellaneous: 106.2,
  },
  WV: {
    state: 'West Virginia',
    stateCode: 'WV',
    overallIndex: 90.5,
    housing: 76.5,
    groceries: 95.2,
    utilities: 101.2,
    transportation: 91.8,
    healthcare: 92.8,
    miscellaneous: 95.5,
  },
  WI: {
    state: 'Wisconsin',
    stateCode: 'WI',
    overallIndex: 93.5,
    housing: 85.2,
    groceries: 97.5,
    utilities: 98.2,
    transportation: 95.8,
    healthcare: 96.5,
    miscellaneous: 95.8,
  },
  WY: {
    state: 'Wyoming',
    stateCode: 'WY',
    overallIndex: 96.2,
    housing: 88.5,
    groceries: 100.5,
    utilities: 93.8,
    transportation: 99.2,
    healthcare: 102.5,
    miscellaneous: 97.5,
  },
};

// Calculate cost of living adjusted salary
export function calculateCOLAdjustedSalary(
  annualSalary: number,
  fromState: string,
  toState: string
): {
  adjustedSalary: number;
  percentageChange: number;
  purchasingPowerDifference: number;
} {
  const fromCOL = costOfLivingByState[fromState]?.overallIndex || 100;
  const toCOL = costOfLivingByState[toState]?.overallIndex || 100;

  // Calculate equivalent salary needed to maintain same purchasing power
  const adjustedSalary = (annualSalary * toCOL) / fromCOL;
  const percentageChange = ((toCOL - fromCOL) / fromCOL) * 100;
  const purchasingPowerDifference = annualSalary - (annualSalary * fromCOL) / toCOL;

  return {
    adjustedSalary: Math.round(adjustedSalary),
    percentageChange: Math.round(percentageChange * 10) / 10,
    purchasingPowerDifference: Math.round(purchasingPowerDifference),
  };
}

// Get states sorted by cost of living
export function getStatesSortedByCOL(ascending: boolean = true): CostOfLivingData[] {
  const states = Object.values(costOfLivingByState);
  return states.sort((a, b) =>
    ascending ? a.overallIndex - b.overallIndex : b.overallIndex - a.overallIndex
  );
}

// Get cost of living category breakdown comparison
export function compareCOLCategories(
  fromState: string,
  toState: string
): { category: string; from: number; to: number; difference: number }[] {
  const from = costOfLivingByState[fromState];
  const to = costOfLivingByState[toState];

  if (!from || !to) return [];

  const categories = [
    { key: 'housing', label: 'Housing' },
    { key: 'groceries', label: 'Groceries' },
    { key: 'utilities', label: 'Utilities' },
    { key: 'transportation', label: 'Transportation' },
    { key: 'healthcare', label: 'Healthcare' },
    { key: 'miscellaneous', label: 'Miscellaneous' },
  ] as const;

  return categories.map(({ key, label }) => ({
    category: label,
    from: from[key],
    to: to[key],
    difference: Math.round((to[key] - from[key]) * 10) / 10,
  }));
}
